# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Publish docs to github pages"
description: "Custom finalize step to publish docs to github pages"
# these inputs are always provided by flowzone, so they must always be defined on the composite action
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
      with:
        node-version: "16"

    - name: Install NPM dependencies
      shell: bash
      run: npm i

    - name: Generate docs
      shell: bash
      run: npm run doc

    - name: Publish generated docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }}
        publish_dir: docs
        publish_branch: docs
